const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Spanish', native: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', native: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', native: 'Deutsch', flag: '🇩🇪' },
  { code: 'ru', name: 'Russian', native: 'Русский', flag: '🇷🇺' },
  { code: 'ja', name: 'Japanese', native: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', native: '한국어', flag: '🇰🇷' },
  { code: 'zh', name: 'Chinese', native: '中文', flag: '🇨🇳' },
  { code: 'pt', name: 'Portuguese', native: 'Português', flag: '🇵🇹' },
  { code: 'it', name: 'Italian', native: 'Italiano', flag: '🇮🇹' },
  { code: 'tr', name: 'Turkish', native: 'Türkçe', flag: '🇹🇷' },
  { code: 'ar', name: 'Arabic', native: 'العربية', flag: '🇸🇦' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', flag: '🇧🇩' },
  { code: 'pl', name: 'Polish', native: 'Polski', flag: '🇵🇱' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands', flag: '🇳🇱' },
  { code: 'sv', name: 'Swedish', native: 'Svenska', flag: '🇸🇪' },
  { code: 'no', name: 'Norwegian', native: 'Norsk', flag: '🇳🇴' },
  { code: 'da', name: 'Danish', native: 'Dansk', flag: '🇩🇰' },
  { code: 'fi', name: 'Finnish', native: 'Suomi', flag: '🇫🇮' },
  { code: 'uk', name: 'Ukrainian', native: 'Українська', flag: '🇺🇦' },
  { code: 'cs', name: 'Czech', native: 'Čeština', flag: '🇨🇿' },
  { code: 'ro', name: 'Romanian', native: 'Română', flag: '🇷🇴' },
  { code: 'hu', name: 'Hungarian', native: 'Magyar', flag: '🇭🇺' },
  { code: 'el', name: 'Greek', native: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'th', name: 'Thai', native: 'ไทย', flag: '🇹🇭' },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ms', name: 'Malay', native: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'tl', name: 'Filipino', native: 'Filipino', flag: '🇵🇭' },
  { code: 'he', name: 'Hebrew', native: 'עברית', flag: '🇮🇱' },
  { code: 'fa', name: 'Persian', native: 'فارسی', flag: '🇮🇷' },
  { code: 'sw', name: 'Swahili', native: 'Kiswahili', flag: '🇰🇪' },
  { code: 'hr', name: 'Croatian', native: 'Hrvatski', flag: '🇭🇷' },
  { code: 'sk', name: 'Slovak', native: 'Slovenčina', flag: '🇸🇰' },
  { code: 'bg', name: 'Bulgarian', native: 'Български', flag: '🇧🇬' },
];

const COUNTRIES = [
  { name: 'United States', flag: '🇺🇸', online: 12847 },
  { name: 'Brazil', flag: '🇧🇷', online: 8234 },
  { name: 'Japan', flag: '🇯🇵', online: 5102 },
  { name: 'Germany', flag: '🇩🇪', online: 3891 },
  { name: 'United Kingdom', flag: '🇬🇧', online: 4523 },
  { name: 'France', flag: '🇫🇷', online: 3214 },
  { name: 'South Korea', flag: '🇰🇷', online: 4087 },
  { name: 'India', flag: '🇮🇳', online: 7653 },
  { name: 'Mexico', flag: '🇲🇽', online: 3456 },
  { name: 'Canada', flag: '🇨🇦', online: 2987 },
  { name: 'Australia', flag: '🇦🇺', online: 2134 },
  { name: 'Russia', flag: '🇷🇺', online: 6543 },
  { name: 'Spain', flag: '🇪🇸', online: 2876 },
  { name: 'Italy', flag: '🇮🇹', online: 2345 },
  { name: 'Turkey', flag: '🇹🇷', online: 3102 },
  { name: 'Argentina', flag: '🇦🇷', online: 1987 },
  { name: 'Colombia', flag: '🇨🇴', online: 1654 },
  { name: 'Poland', flag: '🇵🇱', online: 1823 },
  { name: 'Netherlands', flag: '🇳🇱', online: 1456 },
  { name: 'Thailand', flag: '🇹🇭', online: 2234 },
  { name: 'Indonesia', flag: '🇮🇩', online: 3567 },
  { name: 'Philippines', flag: '🇵🇭', online: 2890 },
  { name: 'Vietnam', flag: '🇻🇳', online: 1987 },
  { name: 'Egypt', flag: '🇪🇬', online: 1543 },
  { name: 'Nigeria', flag: '🇳🇬', online: 1234 },
  { name: 'South Africa', flag: '🇿🇦', online: 987 },
  { name: 'Saudi Arabia', flag: '🇸🇦', online: 1876 },
  { name: 'UAE', flag: '🇦🇪', online: 1432 },
  { name: 'Israel', flag: '🇮🇱', online: 1102 },
  { name: 'Sweden', flag: '🇸🇪', online: 1023 },
  { name: 'Norway', flag: '🇳🇴', online: 876 },
  { name: 'Denmark', flag: '🇩🇰', online: 765 },
  { name: 'Finland', flag: '🇫🇮', online: 654 },
  { name: 'Switzerland', flag: '🇨🇭', online: 987 },
  { name: 'Austria', flag: '🇦🇹', online: 876 },
  { name: 'Belgium', flag: '🇧🇪', online: 765 },
  { name: 'Portugal', flag: '🇵🇹', online: 1098 },
  { name: 'Greece', flag: '🇬🇷', online: 876 },
  { name: 'Czech Republic', flag: '🇨🇿', online: 765 },
  { name: 'Romania', flag: '🇷🇴', online: 654 },
  { name: 'Hungary', flag: '🇭🇺', online: 543 },
  { name: 'Ukraine', flag: '🇺🇦', online: 2345 },
  { name: 'China', flag: '🇨🇳', online: 8765 },
  { name: 'Taiwan', flag: '🇹🇼', online: 1876 },
  { name: 'Malaysia', flag: '🇲🇾', online: 1234 },
  { name: 'Singapore', flag: '🇸🇬', online: 987 },
  { name: 'New Zealand', flag: '🇳🇿', online: 543 },
  { name: 'Ireland', flag: '🇮🇪', online: 654 },
  { name: 'Chile', flag: '🇨🇱', online: 876 },
  { name: 'Peru', flag: '🇵🇪', online: 765 },
  { name: 'Pakistan', flag: '🇵🇰', online: 2345 },
  { name: 'Bangladesh', flag: '🇧🇩', online: 1654 },
  { name: 'Sri Lanka', flag: '🇱🇰', online: 432 },
  { name: 'Nepal', flag: '🇳🇵', online: 345 },
  { name: 'Morocco', flag: '🇲🇦', online: 876 },
  { name: 'Tunisia', flag: '🇹🇳', online: 432 },
  { name: 'Kenya', flag: '🇰🇪', online: 654 },
  { name: 'Ghana', flag: '🇬🇭', online: 432 },
  { name: 'Ethiopia', flag: '🇪🇹', online: 345 },
  { name: 'Tanzania', flag: '🇹🇿', online: 234 },
  { name: 'Iraq', flag: '🇮🇶', online: 765 },
  { name: 'Iran', flag: '🇮🇷', online: 1543 },
  { name: 'Jordan', flag: '🇯🇴', online: 432 },
  { name: 'Lebanon', flag: '🇱🇧', online: 345 },
  { name: 'Kuwait', flag: '🇰🇼', online: 543 },
  { name: 'Qatar', flag: '🇶🇦', online: 432 },
  { name: 'Bahrain', flag: '🇧🇭', online: 234 },
  { name: 'Oman', flag: '🇴🇲', online: 234 },
  { name: 'Croatia', flag: '🇭🇷', online: 345 },
  { name: 'Serbia', flag: '🇷🇸', online: 432 },
  { name: 'Bulgaria', flag: '🇧🇬', online: 345 },
  { name: 'Slovakia', flag: '🇸🇰', online: 321 },
  { name: 'Slovenia', flag: '🇸🇮', online: 234 },
  { name: 'Lithuania', flag: '🇱🇹', online: 234 },
  { name: 'Latvia', flag: '🇱🇻', online: 198 },
  { name: 'Estonia', flag: '🇪🇪', online: 176 },
  { name: 'Iceland', flag: '🇮🇸', online: 123 },
  { name: 'Luxembourg', flag: '🇱🇺', online: 98 },
  { name: 'Malta', flag: '🇲🇹', online: 87 },
  { name: 'Cyprus', flag: '🇨🇾', online: 143 },
  { name: 'Georgia', flag: '🇬🇪', online: 234 },
  { name: 'Armenia', flag: '🇦🇲', online: 176 },
  { name: 'Azerbaijan', flag: '🇦🇿', online: 234 },
  { name: 'Kazakhstan', flag: '🇰🇿', online: 543 },
  { name: 'Uzbekistan', flag: '🇺🇿', online: 345 },
  { name: 'Mongolia', flag: '🇲🇳', online: 123 },
  { name: 'Myanmar', flag: '🇲🇲', online: 234 },
  { name: 'Cambodia', flag: '🇰🇭', online: 198 },
  { name: 'Laos', flag: '🇱🇦', online: 87 },
  { name: 'Cuba', flag: '🇨🇺', online: 123 },
  { name: 'Jamaica', flag: '🇯🇲', online: 234 },
  { name: 'Dominican Republic', flag: '🇩🇴', online: 345 },
  { name: 'Costa Rica', flag: '🇨🇷', online: 234 },
  { name: 'Panama', flag: '🇵🇦', online: 198 },
  { name: 'Ecuador', flag: '🇪🇨', online: 432 },
  { name: 'Venezuela', flag: '🇻🇪', online: 654 },
  { name: 'Bolivia', flag: '🇧🇴', online: 234 },
  { name: 'Paraguay', flag: '🇵🇾', online: 198 },
  { name: 'Uruguay', flag: '🇺🇾', online: 234 },
  { name: 'Honduras', flag: '🇭🇳', online: 176 },
  { name: 'Guatemala', flag: '🇬🇹', online: 234 },
  { name: 'El Salvador', flag: '🇸🇻', online: 143 },
  { name: 'Nicaragua', flag: '🇳🇮', online: 98 },
  { name: 'Algeria', flag: '🇩🇿', online: 654 },
  { name: 'Libya', flag: '🇱🇾', online: 198 },
  { name: 'Sudan', flag: '🇸🇩', online: 234 },
  { name: 'Uganda', flag: '🇺🇬', online: 234 },
  { name: 'Cameroon', flag: '🇨🇲', online: 198 },
  { name: 'Angola', flag: '🇦🇴', online: 176 },
  { name: 'Mozambique', flag: '🇲🇿', online: 123 },
  { name: 'Madagascar', flag: '🇲🇬', online: 87 },
  { name: 'Senegal', flag: '🇸🇳', online: 198 },
  { name: 'Zimbabwe', flag: '🇿🇼', online: 143 },
  { name: 'Zambia', flag: '🇿🇲', online: 123 },
  { name: 'Afghanistan', flag: '🇦🇫', online: 234 },
  { name: 'Yemen', flag: '🇾🇪', online: 176 },
  { name: 'Syria', flag: '🇸🇾', online: 198 },
  { name: 'North Korea', flag: '🇰🇵', online: 0 },
  { name: 'Vatican City', flag: '🇻🇦', online: 0 },
  { name: 'Tuvalu', flag: '🇹🇻', online: 0 },
  { name: 'Nauru', flag: '🇳🇷', online: 0 },
  { name: 'Palau', flag: '🇵🇼', online: 0 },
  { name: 'San Marino', flag: '🇸🇲', online: 12 },
  { name: 'Monaco', flag: '🇲🇨', online: 23 },
  { name: 'Liechtenstein', flag: '🇱🇮', online: 18 },
  { name: 'Andorra', flag: '🇦🇩', online: 34 },
  { name: 'Brunei', flag: '🇧🇳', online: 67 },
  { name: 'Bhutan', flag: '🇧🇹', online: 45 },
  { name: 'Maldives', flag: '🇲🇻', online: 56 },
  { name: 'Fiji', flag: '🇫🇯', online: 43 },
  { name: 'Barbados', flag: '🇧🇧', online: 34 },
  { name: 'Trinidad and Tobago', flag: '🇹🇹', online: 87 },
  { name: 'Bahamas', flag: '🇧🇸', online: 45 },
  { name: 'Suriname', flag: '🇸🇷', online: 23 },
  { name: 'Guyana', flag: '🇬🇾', online: 34 },
  { name: 'Belize', flag: '🇧🇿', online: 23 },
  { name: 'Haiti', flag: '🇭🇹', online: 143 },
  { name: 'Mauritius', flag: '🇲🇺', online: 56 },
  { name: 'Botswana', flag: '🇧🇼', online: 67 },
  { name: 'Namibia', flag: '🇳🇦', online: 45 },
  { name: 'Rwanda', flag: '🇷🇼', online: 87 },
  { name: 'Somalia', flag: '🇸🇴', online: 123 },
  { name: 'Mali', flag: '🇲🇱', online: 67 },
  { name: 'Niger', flag: '🇳🇪', online: 45 },
  { name: 'Chad', flag: '🇹🇩', online: 34 },
  { name: 'Burkina Faso', flag: '🇧🇫', online: 56 },
  { name: 'Benin', flag: '🇧🇯', online: 45 },
  { name: 'Togo', flag: '🇹🇬', online: 34 },
  { name: 'Sierra Leone', flag: '🇸🇱', online: 23 },
  { name: 'Liberia', flag: '🇱🇷', online: 23 },
  { name: 'Ivory Coast', flag: '🇨🇮', online: 123 },
  { name: 'Guinea', flag: '🇬🇳', online: 45 },
  { name: 'Gabon', flag: '🇬🇦', online: 34 },
  { name: 'Congo', flag: '🇨🇬', online: 45 },
  { name: 'DR Congo', flag: '🇨🇩', online: 176 },
  { name: 'Eritrea', flag: '🇪🇷', online: 23 },
  { name: 'Djibouti', flag: '🇩🇯', online: 12 },
  { name: 'Comoros', flag: '🇰🇲', online: 8 },
  { name: 'Lesotho', flag: '🇱🇸', online: 12 },
  { name: 'Eswatini', flag: '🇸🇿', online: 12 },
  { name: 'Equatorial Guinea', flag: '🇬🇶', online: 8 },
  { name: 'Central African Republic', flag: '🇨🇫', online: 8 },
  { name: 'South Sudan', flag: '🇸🇸', online: 23 },
  { name: 'Tajikistan', flag: '🇹🇯', online: 87 },
  { name: 'Turkmenistan', flag: '🇹🇲', online: 34 },
  { name: 'Kyrgyzstan', flag: '🇰🇬', online: 98 },
  { name: 'Papua New Guinea', flag: '🇵🇬', online: 23 },
  { name: 'Solomon Islands', flag: '🇸🇧', online: 8 },
  { name: 'Vanuatu', flag: '🇻🇺', online: 8 },
  { name: 'Samoa', flag: '🇼🇸', online: 12 },
  { name: 'Tonga', flag: '🇹🇴', online: 8 },
  { name: 'Micronesia', flag: '🇫🇲', online: 5 },
  { name: 'Marshall Islands', flag: '🇲🇭', online: 3 },
  { name: 'Kiribati', flag: '🇰🇮', online: 3 },
  { name: 'Timor-Leste', flag: '🇹🇱', online: 23 },
  { name: 'Seychelles', flag: '🇸🇨', online: 12 },
  { name: 'Antigua and Barbuda', flag: '🇦🇬', online: 8 },
  { name: 'Saint Lucia', flag: '🇱🇨', online: 8 },
  { name: 'Grenada', flag: '🇬🇩', online: 5 },
  { name: 'Saint Vincent', flag: '🇻🇨', online: 5 },
  { name: 'Dominica', flag: '🇩🇲', online: 5 },
  { name: 'Saint Kitts and Nevis', flag: '🇰🇳', online: 3 },
  { name: 'Cape Verde', flag: '🇨🇻', online: 23 },
  { name: 'Sao Tome and Principe', flag: '🇸🇹', online: 3 },
  { name: 'Guinea-Bissau', flag: '🇬🇼', online: 5 },
  { name: 'Mauritania', flag: '🇲🇷', online: 45 },
  { name: 'Gambia', flag: '🇬🇲', online: 23 },
  { name: 'Malawi', flag: '🇲🇼', online: 45 },
];

const BLOCKED_EMAIL_DOMAINS = [
  'tempmail.com', 'throwaway.email', 'guerrillamail.com',
  'mailinator.com', 'yopmail.com', 'trashmail.com',
  'sharklasers.com', 'fakeinbox.com', 'dispostable.com',
];

const ALLOWED_EMAIL_DOMAINS = [
  'gmail.com', 'yahoo.com', 'outlook.com', 'hotmail.com',
  'icloud.com', 'protonmail.com', 'mail.ru', 'yandex.ru',
  'aol.com', 'zoho.com', 'live.com', 'msn.com',
];
